### ISSUE TITLE
Build leanr module for template set 2

### ISSUE THREAD

**Issue by sjspielman** [sjspielman/cb2r-ds-summer2020#5]
A new template set is there! Let me know if/when things are confusing - some of the format is a little different here, and I am *even better* at typos than usual!

Note, going forward, don't add the HTML output from the learnr module (just ignore the file and present it's not there - I've set up the repository to do that as well). Only the Rmd is necessary to track.

Finally, before making your branch, be extra sure you've synced with my master. Enjoy!

**Comment by sjspielman** [comment]
@shemaiah-s confirm with me once you see this by commenting here - thanks!!

**Comment by shemaiah-s** [comment]
Just saw it! Sorry I was out of town yesterday. I'll start working on this today :)

**Comment by sjspielman** [comment]
Totally fine!!
